DATA = [
    {
        'name': 'Sam',
        'age': 72,
        'organization': 'Google',
        'position': 'Technical Coach',
        'language': 'python',
    },
    {
        'name': 'Iliugna',
        'age': 33,
        'organization': 'Globant',
        'position': 'UX Designer',
        'language': 'javascript',
    },
    {
        'name': 'Xiao',
        'age': 16,
        'organization': 'UN',
        'position': 'Associate',
        'language': 'ruby',
    },
    {
        'name': 'Gabrielle',
        'age': 20,
        'organization': 'Google',
        'position': 'Associate',
        'language': 'javascript',
    },
    {
        'name': 'Isabelle',
        'age': 30,
        'organization': 'Google',
        'position': 'QA Manager',
        'language': 'java',
    },
    {
        'name': 'Karo',
        'age': 23,
        'organization': 'Everis',
        'position': 'Backend Developer',
        'language': 'python',
    },
    {
        'name': 'Arieo',
        'age': 32,
        'organization': 'Rappi',
        'position': 'Support',
        'language': '',
    },
    {
        'name': 'Thomas',
        'age': 17,
        'organization': '',
        'position': 'Student',
        'language': 'go',
    },
    {
        'name': 'Pablo',
        'age': 92,
        'organization': 'Master Doubts',
        'position': 'Human Resources Manager',
        'language': 'python',
    },
    {
        'name': 'Chris',
        'age': 56,
        'organization': 'Python Organization',
        'position': 'Language Maker',
        'language': 'python',
    },
]
